// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.261
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Conference.Specflow.Features.Registration.Discounts
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PromotionalCodeScenariosForApplyingPromotionalCodesToSeatTypesFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Discounts.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Promotional Code scenarios for applying Promotional Codes to Seat Types", "In order to apply a Promotional Code for one ore more Seat Types\r\nAs a Registrant" +
                    "\r\nI want to be able to enter a Promotional Code and get the specified price redu" +
                    "ction", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "Promotional Code scenarios for applying Promotional Codes to Seat Types")))
            {
                Conference.Specflow.Features.Registration.Discounts.PromotionalCodeScenariosForApplyingPromotionalCodesToSeatTypesFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "rate"});
            table1.AddRow(new string[] {
                        "General admission",
                        "$199"});
            table1.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "$500"});
            table1.AddRow(new string[] {
                        "Additional cocktail party",
                        "$50"});
#line 7
 testRunner.Given("the list of the available Order Items for the CQRS summit 2012 conference", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Promotional Code",
                        "Discount",
                        "Quota",
                        "Scope",
                        "Cumulative"});
            table2.AddRow(new string[] {
                        "SPEAKER123",
                        "100%",
                        "Unlimited",
                        "All",
                        ""});
            table2.AddRow(new string[] {
                        "VOLUNTEER",
                        "100%",
                        "Unlimited",
                        "General admission",
                        ""});
            table2.AddRow(new string[] {
                        "COPRESENTER",
                        "10%",
                        "Unlimited",
                        "Additional cocktail party",
                        "Exclusive"});
            table2.AddRow(new string[] {
                        "WS10",
                        "$20",
                        "Unlimited",
                        "All",
                        "VOLUNTEER"});
            table2.AddRow(new string[] {
                        "1TIMEPRECON",
                        "50%",
                        "Single",
                        "Pre-con Workshop with Greg Young",
                        ""});
            table2.AddRow(new string[] {
                        "CONFONLY",
                        "$50",
                        "Single",
                        "General admission, Pre-con Workshop with Greg Young",
                        ""});
#line 12
 testRunner.And("the Promotional Codes", ((string)(null)), table2);
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Full Promotional Code for all selected items")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void FullPromotionalCodeForAllSelectedItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Full Promotional Code for all selected items", new string[] {
                        "ignore"});
#line 24
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table3.AddRow(new string[] {
                        "General admission",
                        "3"});
            table3.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table3.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 25
 testRunner.Given("the selected available Order Items", ((string)(null)), table3);
#line 30
 testRunner.And("the total amount should be of $1197");
#line 31
 testRunner.When("the Registrant apply the \'SPEAKER123\' Promotional Code");
#line 32
 testRunner.Then("the \'SPEAKER123\' Promo code should show a value of -$1197");
#line 33
 testRunner.And("the total amount should be of $0");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Partial Promotional Code for all selected items")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void PartialPromotionalCodeForAllSelectedItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial Promotional Code for all selected items", new string[] {
                        "ignore"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table4.AddRow(new string[] {
                        "General admission",
                        "3"});
            table4.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table4.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 39
 testRunner.Given("the selected available Order Items", ((string)(null)), table4);
#line 44
 testRunner.And("the total amount should be of $1197");
#line 45
 testRunner.When("the Registrant apply the \'VOLUNTEER\' Promotional Code");
#line 46
 testRunner.Then("the \'VOLUNTEER\' Promo code should show a value of -$597");
#line 47
 testRunner.And("the total amount should be of $600");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Partial Promotional Code for none of the selected items")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void PartialPromotionalCodeForNoneOfTheSelectedItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial Promotional Code for none of the selected items", new string[] {
                        "ignore"});
#line 52
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table5.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table5.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 53
 testRunner.Given("the selected available Order Items", ((string)(null)), table5);
#line 57
 testRunner.And("the total amount should be of $600");
#line 58
 testRunner.When("the Registrant apply the \'VOLUNTEER\' Promotional Code");
#line 59
 testRunner.Then("the \'VOLUNTEER\' Promo code will not be applied and an error message will inform a" +
                    "bout the problem");
#line 60
 testRunner.And("the total amount should be of $600");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Cumulative Promotional Codes")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void CumulativePromotionalCodes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Cumulative Promotional Codes", new string[] {
                        "ignore"});
#line 65
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table6.AddRow(new string[] {
                        "General admission",
                        "3"});
            table6.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table6.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 66
 testRunner.Given("the selected available Order Items", ((string)(null)), table6);
#line 71
 testRunner.And("the total amount should be of $1197");
#line 72
 testRunner.When("the Registrant apply the \'COPRESENTER\' Promotional Code");
#line 73
 testRunner.And("the Registrant apply the \'WS10\' Promotional Code");
#line 74
 testRunner.Then("the \'COPRESENTER\' Promotional Code item should show a value of -$10");
#line 75
 testRunner.And("the \'WS10\' Promotional Code item should show a value of -$20");
#line 76
 testRunner.And("the total amount should be of $1167");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Single use Promotional Code")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void SingleUsePromotionalCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Single use Promotional Code", new string[] {
                        "ignore"});
#line 81
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table7.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table7.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 82
 testRunner.Given("the selected available Order Items", ((string)(null)), table7);
#line 86
 testRunner.And("the total amount should be of $600");
#line 87
 testRunner.And("the Registrant apply the \'1TIMEPRECON\' Promotional Code");
#line 88
 testRunner.And("the total amount should be of $350");
#line 89
 testRunner.And("the Registrant proceed to complete the registration");
#line 90
 testRunner.And("the Registrant selects the Event Registration");
#line 91
 testRunner.When("the Registrant apply the \'1TIMEPRECON\' Promotional Code");
#line 92
 testRunner.Then("the \'1TIMEPRECON\' Promo code will not be applied and an error message will inform" +
                    " about the problem");
#line 93
 testRunner.And("the total amount should be of $600");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Mutually exclusive Promotional Code")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void MutuallyExclusivePromotionalCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Mutually exclusive Promotional Code", new string[] {
                        "ignore"});
#line 98
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table8.AddRow(new string[] {
                        "General admission",
                        "3"});
            table8.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table8.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 99
 testRunner.Given("the selected available Order Items", ((string)(null)), table8);
#line 104
 testRunner.And("the total amount should be of $1197");
#line 105
 testRunner.When("the Registrant apply the \'COPRESENTER\' Promotional Code");
#line 106
 testRunner.And("the Registrant apply the \'VOLUNTEER\' Promotional Code");
#line 107
 testRunner.Then("the \'VOLUNTEER\' Promo code will not be applied and an error message will inform a" +
                    "bout the problem");
#line 108
 testRunner.And("the \'COPRESENTER\' Promotional Code item should show a value of -$10");
#line 109
 testRunner.And("the total amount should be of $1187");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Combine only Promotional Code")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void CombineOnlyPromotionalCode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Combine only Promotional Code", new string[] {
                        "ignore"});
#line 114
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table9.AddRow(new string[] {
                        "General admission",
                        "3"});
            table9.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table9.AddRow(new string[] {
                        "Additional cocktail party",
                        "2"});
#line 115
 testRunner.Given("the selected available Order Items", ((string)(null)), table9);
#line 120
 testRunner.And("the total amount should be of $1197");
#line 121
 testRunner.When("the Registrant apply the \'WS10\' Promotional Code");
#line 122
 testRunner.And("the Registrant apply the \'VOLUNTEER\' Promotional Code");
#line 123
 testRunner.Then("the \'VOLUNTEER\' Promo code should show a value of -$597");
#line 124
 testRunner.And("the \'WS10\' Promotional Code item should show a value of -$10");
#line 125
 testRunner.And("the total amount should be of $590");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Partial scope")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Promotional Code scenarios for applying Promotional Codes to Seat Types")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.IgnoreAttribute()]
        public virtual void PartialScope()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Partial scope", new string[] {
                        "ignore"});
#line 130
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table10.AddRow(new string[] {
                        "General admission",
                        "1"});
            table10.AddRow(new string[] {
                        "Pre-con Workshop with Greg Young",
                        "1"});
            table10.AddRow(new string[] {
                        "Additional cocktail party",
                        "1"});
#line 131
 testRunner.Given("the selected available Order Items", ((string)(null)), table10);
#line 136
 testRunner.And("the total amount should be of $749");
#line 137
 testRunner.When("the Registrant apply the \'CONFONLY\' Promotional Code");
#line 138
 testRunner.Then("the \'CONFONLY\' Promo code should show a value of -$50");
#line 139
 testRunner.And("the total amount should be of $699");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
