// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.269
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Conference.Specflow.Features.UserInterface.Views.Registration
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature : Xunit.IUseFixture<SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SelfRegistrationReservationWithPartialAvailability.feature"
#line hidden
        
        public SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Self Registrant scenarios for making a Reservation for a Conference site with Ord" +
                    "er Items partially available", "In order to reserve Seats for a Conference\r\nAs an Attendee\r\nI want to be able to " +
                    "select an Order Item from one or many of the available and or waitlisted Order I" +
                    "tems and make a Reservation", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 20
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "rate",
                        "quota"});
            table1.AddRow(new string[] {
                        "General admission",
                        "$199",
                        "20"});
            table1.AddRow(new string[] {
                        "CQRS Workshop",
                        "$500",
                        "20"});
            table1.AddRow(new string[] {
                        "Additional cocktail party",
                        "$50",
                        "20"});
#line 21
 testRunner.Given("the list of the available Order Items for the CQRS summit 2012 conference", ((string)(null)), table1);
#line hidden
        }
        
        public virtual void SetFixture(SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Self Registrant scenarios for making a Reservation for a Conference site with Ord" +
            "er Items partially available")]
        [Xunit.TraitAttribute("Description", "All the Order Items are selected and none are available, then none get reserved")]
        public virtual void AllTheOrderItemsAreSelectedAndNoneAreAvailableThenNoneGetReserved()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All the Order Items are selected and none are available, then none get reserved", ((string[])(null)));
#line 30
 this.ScenarioSetup(scenarioInfo);
#line 20
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table2.AddRow(new string[] {
                        "General admission",
                        "1"});
            table2.AddRow(new string[] {
                        "CQRS Workshop",
                        "1"});
            table2.AddRow(new string[] {
                        "Additional cocktail party",
                        "1"});
#line 31
  testRunner.Given("the selected Order Items", ((string)(null)), table2);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type"});
            table3.AddRow(new string[] {
                        "General admission"});
            table3.AddRow(new string[] {
                        "CQRS Workshop"});
            table3.AddRow(new string[] {
                        "Additional cocktail party"});
#line 36
 testRunner.And("these Seat Types become unavailable before the Registrant makes the reservation", ((string)(null)), table3);
#line 41
 testRunner.When("the Registrant proceeds to make the Reservation with seats already reserved");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "selected",
                        "message"});
            table4.AddRow(new string[] {
                        "General admission",
                        "",
                        "Sold out"});
            table4.AddRow(new string[] {
                        "CQRS Workshop",
                        "",
                        "Sold out"});
            table4.AddRow(new string[] {
                        "Additional cocktail party",
                        "",
                        "Sold out"});
#line 42
 testRunner.Then("the Registrant is offered to select any of these available seats", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Self Registrant scenarios for making a Reservation for a Conference site with Ord" +
            "er Items partially available")]
        [Xunit.TraitAttribute("Description", "All the Order Items are selected and two are not available, then one get reserved" +
            " and two not")]
        public virtual void AllTheOrderItemsAreSelectedAndTwoAreNotAvailableThenOneGetReservedAndTwoNot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All the Order Items are selected and two are not available, then one get reserved" +
                    " and two not", ((string[])(null)));
#line 51
 this.ScenarioSetup(scenarioInfo);
#line 20
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table5.AddRow(new string[] {
                        "General admission",
                        "1"});
            table5.AddRow(new string[] {
                        "CQRS Workshop",
                        "1"});
            table5.AddRow(new string[] {
                        "Additional cocktail party",
                        "1"});
#line 52
  testRunner.Given("the selected Order Items", ((string)(null)), table5);
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type"});
            table6.AddRow(new string[] {
                        "CQRS Workshop"});
            table6.AddRow(new string[] {
                        "Additional cocktail party"});
#line 57
 testRunner.And("these Seat Types become unavailable before the Registrant makes the reservation", ((string)(null)), table6);
#line 61
 testRunner.When("the Registrant proceeds to make the Reservation with seats already reserved");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "selected",
                        "message"});
            table7.AddRow(new string[] {
                        "General admission",
                        "0",
                        ""});
            table7.AddRow(new string[] {
                        "CQRS Workshop",
                        "",
                        "Sold out"});
            table7.AddRow(new string[] {
                        "Additional cocktail party",
                        "",
                        "Sold out"});
#line 62
 testRunner.Then("the Registrant is offered to select any of these available seats", ((string)(null)), table7);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Self Registrant scenarios for making a Reservation for a Conference site with Ord" +
            "er Items partially available")]
        [Xunit.TraitAttribute("Description", "All the Order Items are selected, one is partially available and one none availab" +
            "le, then two get reserved and one not")]
        public virtual void AllTheOrderItemsAreSelectedOneIsPartiallyAvailableAndOneNoneAvailableThenTwoGetReservedAndOneNot()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All the Order Items are selected, one is partially available and one none availab" +
                    "le, then two get reserved and one not", ((string[])(null)));
#line 72
 this.ScenarioSetup(scenarioInfo);
#line 20
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table8.AddRow(new string[] {
                        "General admission",
                        "1"});
            table8.AddRow(new string[] {
                        "CQRS Workshop",
                        "1"});
            table8.AddRow(new string[] {
                        "Additional cocktail party",
                        "1"});
#line 73
  testRunner.Given("the selected Order Items", ((string)(null)), table8);
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table9.AddRow(new string[] {
                        "CQRS Workshop",
                        "10"});
            table9.AddRow(new string[] {
                        "Additional cocktail party",
                        ""});
#line 78
 testRunner.And("these Seat Types become unavailable before the Registrant makes the reservation", ((string)(null)), table9);
#line 82
 testRunner.And("the Registrant proceeds to make the Reservation with seats already reserved");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "selected",
                        "message"});
            table10.AddRow(new string[] {
                        "General admission",
                        "0",
                        ""});
            table10.AddRow(new string[] {
                        "CQRS Workshop",
                        "0",
                        ""});
            table10.AddRow(new string[] {
                        "Additional cocktail party",
                        "",
                        "Sold out"});
#line 83
 testRunner.And("the Registrant is offered to select any of these available seats", ((string)(null)), table10);
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table11.AddRow(new string[] {
                        "General admission",
                        "1"});
            table11.AddRow(new string[] {
                        "CQRS Workshop",
                        "1"});
#line 88
 testRunner.And("the selected Order Items", ((string)(null)), table11);
#line 92
 testRunner.And("the total should read $699");
#line 93
 testRunner.When("the Registrant proceeds to make the Reservation");
#line 94
 testRunner.Then("the Reservation is confirmed for all the selected Order Items");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "seat type",
                        "quantity"});
            table12.AddRow(new string[] {
                        "General admission",
                        "1"});
            table12.AddRow(new string[] {
                        "CQRS Workshop",
                        "1"});
#line 95
 testRunner.And("these Order Items should be reserved", ((string)(null)), table12);
#line 99
 testRunner.And("the total should read $699");
#line 100
 testRunner.And("the countdown is started");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SelfRegistrantScenariosForMakingAReservationForAConferenceSiteWithOrderItemsPartiallyAvailableFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
