// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:2.0.50727.5448
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Conference.Specflow.Features.Registration.SeatAssignments
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature : Xunit.IUseFixture<RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "FullAssignments.feature"
#line hidden
        
        public RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Registrant workflow for assigning all the registered Order Items.", "", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "First name",
                        "Last name",
                        "email address",
                        "Seat type"});
            table1.AddRow(new string[] {
                        "John",
                        "Smith",
                        "johnsmith@contoso.com",
                        "General admission"});
            table1.AddRow(new string[] {
                        "John",
                        "Smith",
                        "johnsmith@contoso.com",
                        "Additional cocktail party"});
#line 4
 testRunner.Given("the individual purchased Seats", ((string)(null)), table1);
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "First name",
                        "Last name",
                        "email address",
                        "Seat type"});
            table2.AddRow(new string[] {
                        "William",
                        "Smith",
                        "William@Smith.com",
                        "General admission"});
            table2.AddRow(new string[] {
                        "John",
                        "Doe",
                        "JohnDoe@live.com",
                        "General admission"});
            table2.AddRow(new string[] {
                        "Oliver",
                        "Smith",
                        "Oliver@Smith.com",
                        "Pre-con Workshop with Greg Young"});
            table2.AddRow(new string[] {
                        "Tim",
                        "Martin",
                        "Tim@Martin.com",
                        "Pre-con Workshop with Greg Young"});
            table2.AddRow(new string[] {
                        "Mani",
                        "Kris",
                        "Mani@Kris.com",
                        "Additional cocktail party"});
            table2.AddRow(new string[] {
                        "Jim",
                        "John",
                        "Jim@John.com",
                        "Additional cocktail party"});
#line 8
 testRunner.And("the group purchased Seats", ((string)(null)), table2);
#line hidden
        }
        
        public virtual void SetFixture(RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Registrant workflow for assigning all the registered Order Items.")]
        [Xunit.TraitAttribute("Description", "Allocate all purchased Seats for an individual")]
        public virtual void AllocateAllPurchasedSeatsForAnIndividual()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Allocate all purchased Seats for an individual", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 19
testRunner.Given("the ConfirmSuccessfulRegistration for the selected Order Items");
#line 20
testRunner.And("the Order Access code is 6789");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "First name",
                        "Last name",
                        "email address",
                        "Seat type"});
            table3.AddRow(new string[] {
                        "John",
                        "Smith",
                        "johnsmith@contoso.com",
                        "General admission"});
            table3.AddRow(new string[] {
                        "John",
                        "Smith",
                        "johnsmith@contoso.com",
                        "Additional cocktail party"});
#line 21
testRunner.And("the Registrant assign the infividual purchased Seats to attendees as following", ((string)(null)), table3);
#line 25
testRunner.Then("the Registrant should get a Seat assignment confirmation");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Access code",
                        "email address",
                        "Seat type"});
            table4.AddRow(new string[] {
                        "6789-1",
                        "johnsmith@contoso.com",
                        "General admission"});
            table4.AddRow(new string[] {
                        "6789-2",
                        "johnsmith@contoso.com",
                        "Additional cocktail party"});
#line 26
testRunner.And("the Attendees should get an email informing about the conference and the Seat Typ" +
                    "e with Seat Access Code", ((string)(null)), table4);
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute()]
        [Xunit.TraitAttribute("FeatureTitle", "Registrant workflow for assigning all the registered Order Items.")]
        [Xunit.TraitAttribute("Description", "Allocate all purchased Seats for a group")]
        public virtual void AllocateAllPurchasedSeatsForAGroup()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Allocate all purchased Seats for a group", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 3
this.FeatureBackground();
#line 33
testRunner.Given("the ConfirmSuccessfulRegistration");
#line 34
testRunner.And("the order access code is 6789");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "First name",
                        "Last name",
                        "email address",
                        "Seat type"});
            table5.AddRow(new string[] {
                        "William",
                        "Smith",
                        "William@Smith.com",
                        "General admission"});
            table5.AddRow(new string[] {
                        "John",
                        "Doe",
                        "JohnDoe@live.com",
                        "General admission"});
            table5.AddRow(new string[] {
                        "Oliver",
                        "Smith",
                        "Oliver@Smith.com",
                        "Pre-con Workshop with Greg Young"});
            table5.AddRow(new string[] {
                        "Tim",
                        "Martin",
                        "Tim@Martin.com",
                        "Pre-con Workshop with Greg Young"});
            table5.AddRow(new string[] {
                        "Mani",
                        "Kris",
                        "Mani@Kris.com",
                        "Additional cocktail party"});
            table5.AddRow(new string[] {
                        "Jim",
                        "John",
                        "Jim@John.com",
                        "Additional cocktail party"});
#line 35
testRunner.And("the Registrant assign the group purchased Seats to attendees as following", ((string)(null)), table5);
#line 43
testRunner.Then("the Registrant should get a Seat Assignment confirmation");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Access code",
                        "email address",
                        "Seat type"});
            table6.AddRow(new string[] {
                        "6789-1",
                        "William@Smith.com",
                        "General admission"});
            table6.AddRow(new string[] {
                        "6789-2",
                        "JohnDoe@live.com",
                        "General admission"});
            table6.AddRow(new string[] {
                        "6789-3",
                        "Oliver@Smith.com",
                        "Pre-con Workshop with Greg Young"});
            table6.AddRow(new string[] {
                        "6789-4",
                        "Tim@Martin.com",
                        "Pre-con Workshop with Greg Young"});
            table6.AddRow(new string[] {
                        "6789-5",
                        "Mani@Kris.com",
                        "Additional cocktail party"});
            table6.AddRow(new string[] {
                        "6789-6",
                        "Jim@John.com",
                        "Additional cocktail party"});
#line 44
testRunner.And("the Attendees should get an email informing about the conference and the Seat Typ" +
                    "e with Seat Access Code", ((string)(null)), table6);
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RegistrantWorkflowForAssigningAllTheRegisteredOrderItems_Feature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
